# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/oppo/CPH1859/setup-makefiles.sh

PRODUCT_COPY_FILES += \
	vendor/oppo/CPH1859/proprietary/bin/aal:$(TARGET_COPY_OUT_SYSTEM)/bin/aal \
	vendor/oppo/CPH1859/proprietary/bin/aee:$(TARGET_COPY_OUT_SYSTEM)/bin/aee \
	vendor/oppo/CPH1859/proprietary/bin/aee_aed:$(TARGET_COPY_OUT_SYSTEM)/bin/aee_aed \
	vendor/oppo/CPH1859/proprietary/bin/aee_aed64:$(TARGET_COPY_OUT_SYSTEM)/bin/aee_aed64 \
	vendor/oppo/CPH1859/proprietary/bin/aee_archive:$(TARGET_COPY_OUT_SYSTEM)/bin/aee_archive \
	vendor/oppo/CPH1859/proprietary/bin/aee_core_forwarder:$(TARGET_COPY_OUT_SYSTEM)/bin/aee_core_forwarder \
	vendor/oppo/CPH1859/proprietary/bin/aee_dumpstate:$(TARGET_COPY_OUT_SYSTEM)/bin/aee_dumpstate \
	vendor/oppo/CPH1859/proprietary/bin/asserttip:$(TARGET_COPY_OUT_SYSTEM)/bin/asserttip \
	vendor/oppo/CPH1859/proprietary/bin/atci_service_sys:$(TARGET_COPY_OUT_SYSTEM)/bin/atci_service_sys \
	vendor/oppo/CPH1859/proprietary/bin/AudioSetParam:$(TARGET_COPY_OUT_SYSTEM)/bin/AudioSetParam \
	vendor/oppo/CPH1859/proprietary/bin/badblocks:$(TARGET_COPY_OUT_SYSTEM)/bin/badblocks \
	vendor/oppo/CPH1859/proprietary/bin/common_dcs:$(TARGET_COPY_OUT_SYSTEM)/bin/common_dcs \
	vendor/oppo/CPH1859/proprietary/bin/connsyslogger:$(TARGET_COPY_OUT_SYSTEM)/bin/connsyslogger \
	vendor/oppo/CPH1859/proprietary/bin/datafree:$(TARGET_COPY_OUT_SYSTEM)/bin/datafree \
	vendor/oppo/CPH1859/proprietary/bin/emdlogger1:$(TARGET_COPY_OUT_SYSTEM)/bin/emdlogger1 \
	vendor/oppo/CPH1859/proprietary/bin/emdlogger2:$(TARGET_COPY_OUT_SYSTEM)/bin/emdlogger2 \
	vendor/oppo/CPH1859/proprietary/bin/emdlogger3:$(TARGET_COPY_OUT_SYSTEM)/bin/emdlogger3 \
	vendor/oppo/CPH1859/proprietary/bin/emdlogger5:$(TARGET_COPY_OUT_SYSTEM)/bin/emdlogger5 \
	vendor/oppo/CPH1859/proprietary/bin/em_svr:$(TARGET_COPY_OUT_SYSTEM)/bin/em_svr	 \
	vendor/oppo/CPH1859/proprietary/bin/fatlabel:$(TARGET_COPY_OUT_SYSTEM)/bin/fatlabel \
	vendor/oppo/CPH1859/proprietary/bin/fsck.fat:$(TARGET_COPY_OUT_SYSTEM)/bin/fsck.fat \
	vendor/oppo/CPH1859/proprietary/bin/ged_srv:$(TARGET_COPY_OUT_SYSTEM)/bin/ged_srv \
	vendor/oppo/CPH1859/proprietary/bin/iozone:$(TARGET_COPY_OUT_SYSTEM)/bin/iozone \
	vendor/oppo/CPH1859/proprietary/bin/iwpriv:$(TARGET_COPY_OUT_SYSTEM)/bin/iwpriv \
	vendor/oppo/CPH1859/proprietary/bin/kpoc_charger:$(TARGET_COPY_OUT_SYSTEM)/bin/kpoc_charger \
	vendor/oppo/CPH1859/proprietary/bin/lbs_dbg:$(TARGET_COPY_OUT_SYSTEM)/bin/lbs_dbg \
	vendor/oppo/CPH1859/proprietary/bin/lcdc_screen_cap:$(TARGET_COPY_OUT_SYSTEM)/bin/lcdc_screen_cap \
	vendor/oppo/CPH1859/proprietary/bin/loghidlsysservice:$(TARGET_COPY_OUT_SYSTEM)/bin/loghidlsysservice \
	vendor/oppo/CPH1859/proprietary/bin/mdlogger:$(TARGET_COPY_OUT_SYSTEM)/bin/mdlogger \
	vendor/oppo/CPH1859/proprietary/bin/md_monitor:$(TARGET_COPY_OUT_SYSTEM)/bin/md_monitor \
	vendor/oppo/CPH1859/proprietary/bin/md_monitor_ctrl:$(TARGET_COPY_OUT_SYSTEM)/bin/md_monitor_ctrl \
	vendor/oppo/CPH1859/proprietary/bin/memtester_eng:$(TARGET_COPY_OUT_SYSTEM)/bin/memtester_eng \
	vendor/oppo/CPH1859/proprietary/bin/met-cmd:$(TARGET_COPY_OUT_SYSTEM)/bin/met-cmd \
	vendor/oppo/CPH1859/proprietary/bin/met_log_d:$(TARGET_COPY_OUT_SYSTEM)/bin/met_log_d \
	vendor/oppo/CPH1859/proprietary/bin/mkexfat:$(TARGET_COPY_OUT_SYSTEM)/bin/mkexfat \
	vendor/oppo/CPH1859/proprietary/bin/mkntfs:$(TARGET_COPY_OUT_SYSTEM)/bin/mkntfs \
	vendor/oppo/CPH1859/proprietary/bin/mobile_log_d:$(TARGET_COPY_OUT_SYSTEM)/bin/mobile_log_d \
	vendor/oppo/CPH1859/proprietary/bin/motorcontrol:$(TARGET_COPY_OUT_SYSTEM)/bin/motorcontrol \
	vendor/oppo/CPH1859/proprietary/bin/mtk_camdumpserver:$(TARGET_COPY_OUT_SYSTEM)/bin/mtk_camdumpserver \
	vendor/oppo/CPH1859/proprietary/bin/neo:$(TARGET_COPY_OUT_SYSTEM)/bin/neo \
	vendor/oppo/CPH1859/proprietary/bin/netdiag:$(TARGET_COPY_OUT_SYSTEM)/bin/netdiag \
	vendor/oppo/CPH1859/proprietary/bin/ntfs-3g:$(TARGET_COPY_OUT_SYSTEM)/bin/ntfs-3g \
	vendor/oppo/CPH1859/proprietary/bin/ntfsfix:$(TARGET_COPY_OUT_SYSTEM)/bin/ntfsfix \
	vendor/oppo/CPH1859/proprietary/bin/oae_server:$(TARGET_COPY_OUT_SYSTEM)/bin/oae_server \
	vendor/oppo/CPH1859/proprietary/bin/odexmove:$(TARGET_COPY_OUT_SYSTEM)/bin/odexmove \
	vendor/oppo/CPH1859/proprietary/bin/rtt:$(TARGET_COPY_OUT_SYSTEM)/bin/rtt \
	vendor/oppo/CPH1859/proprietary/bin/rutilsdaemon:$(TARGET_COPY_OUT_SYSTEM)/bin/rutilsdaemon \
	vendor/oppo/CPH1859/proprietary/bin/self-init-system:$(TARGET_COPY_OUT_SYSTEM)/bin/self-init-system \
	vendor/oppo/CPH1859/proprietary/bin/sn:$(TARGET_COPY_OUT_SYSTEM)/bin/sn \
	vendor/oppo/CPH1859/proprietary/bin/sspm_log_writer:$(TARGET_COPY_OUT_SYSTEM)/bin/sspm_log_writer \
	vendor/oppo/CPH1859/proprietary/bin/terservice:$(TARGET_COPY_OUT_SYSTEM)/bin/terservice \
	vendor/oppo/CPH1859/proprietary/bin/tertestclient:$(TARGET_COPY_OUT_SYSTEM)/bin/tertestclient \
	vendor/oppo/CPH1859/proprietary/bin/tinycap:$(TARGET_COPY_OUT_SYSTEM)/bin/tinycap \
	vendor/oppo/CPH1859/proprietary/bin/tinymix:$(TARGET_COPY_OUT_SYSTEM)/bin/tinymix \
	vendor/oppo/CPH1859/proprietary/bin/tinypcminfo:$(TARGET_COPY_OUT_SYSTEM)/bin/tinypcminfo \
	vendor/oppo/CPH1859/proprietary/bin/tinyplay:$(TARGET_COPY_OUT_SYSTEM)/bin/tinyplay \
	vendor/oppo/CPH1859/proprietary/bin/tunman:$(TARGET_COPY_OUT_SYSTEM)/bin/tunman \
	vendor/oppo/CPH1859/proprietary/bin/vtservice:$(TARGET_COPY_OUT_SYSTEM)/bin/vtservice \
	vendor/oppo/CPH1859/proprietary/bin/wmt_check_patch:$(TARGET_COPY_OUT_SYSTEM)/bin/wmt_check_patch




PRODUCT_PACKAGES += \
    SoterService
